### ISSUE TITLE
Can I run this vba-link on macOS?

### ISSUE THREAD

**Issue by Yuta32** [luckytyphlosion/vba-link#1]
Hello.
I want to play MMBN6 using vba-link.
I'm trying to get vba-link to work on macOS and found your Github repositoyry.

Now, when I try to clone this repository and run "./setup.sh", it doesn't work.
Is this vba-link designed to work on macOS?

I would appreciate your answer.

Sincerely,

**Comment by RealDoigt** [comment]
The description says it's designed for Linux.

**Comment by luckytyphlosion** [comment]
This repository is turbodead and will not become active again.
